---
title: "Git them all!" 
subtitle: "..A far too short story!" 
author: "(Steven Marcel Bißantz)"
date: "`r Sys.Date()`"
output:
  revealjs::revealjs_presentation:
    theme: blood
    highlight: pygments
    center: true
    slide_level: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Prologue 
...numerous prerequisites

## 1st Aid (Xcode)

1. `xcode-select -p`
2. `xcode-select --install`

see:  <https://github.com/sbissantz/rarp/setup.md>

## 2nd Aid (SSH)

1. `ls -ld .ssh`
2. `ssh-keygen -t rsa -C "foo@bar.com"`

see:  <https://github.com/sbissantz/rarp/ssh.md>

## 3rd Aid (Git) 

1. `Cmd + Space > "Terminal"`
2. `git --version`

## 4th Aid (install!) 

1. Manually? (..go ahead!)
2. `brew install git` 

Windows: <https://git-scm.com/download/win>

## 5th Aid (Homebrew)
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

## 6th Aid (Github)
<https://github.com>

## 7th Aid (Gedit)
`brew install gedit`

# Git Kick Off 

Yaay!

## What is Git?
A revision control system (VCS)

## Why use Git?

1. Checksumming (track!)
2. DVCS (safe!)
3. Nanny McGit (organize!)

## Why Git @CMD?
..to get the full sense of satisfaction!

  CMD $\rightarrow$ GUI
  
  CMD $\nleftarrow$ GUI

## (Remote) Repository
A commited & SHA1-hased stream of versions 

## SHA-1 hash

`62c4d1d6ec05050c439ec384b2bba11cd64d37a0`

\#Chechsumming \#commit! 

## The 3 States 
(modified, staged, committed)

## Workflow (queued)
(modify, stage, commit)

# Global User Setup 
(only @1st_time)

## Setup (obligatory)

- `git config --global user.name "John Doe"`
- `git config --global user.email johndoe@example.com`

## Additionals 

- `git config --global color.ui true`
- `git config --global core.editor nvim`
- `git config --global core.editor gedit`
- `git config --global format.pretty oneline`

## Show setup

- `git config user.name`
- `git config --list`
- `git config --list --show origin`

## Your turn! (5-10 min)

Set up your Git user account! 

\#BreakOutRooms!?

# Workflow 

1. initialize!
2. Grrrr!$^*$
3. push!

$^*$: (G)it (r)outine (r)outine (r)outine (r)outine...

## initialize!

1. `mkdir -p test_dir ; cd test_dir`
2. `pwd`
3. `git init`

# Grrr! (Git Routine) 

1. modify!
2. stage!
3. commit!

# Git Routine (cmds & dirs) 

check Repo status: `git status`

1. modifiy! (WD) 
2. `git add` (INDEX)
3. `git commit` (HEAD)

## modify!

1. `touch test_{1..9}`
2. `echo "I am a test" >> test_{1..9}"`
3. `cat test_{1..9}`

## stage!

- `git add "test_1"`
- `git add .`
- `git add -i`

## commit!

- `git commit` (core.editor)
- `git commit -m "typos"`
- `git commit -a`
- `git commit -a -m "typos"`

## correct commit!

`git commit --amend -m "typos"`

## push?

STOP! What is missing?

## push?!

Ah, the remote repository..

e.g.: @GitHub

## @Github & local (push setup)

1. `"Settings" > "SSH and GPG keys"`
2. `pbcopy < ~/.ssh/id_rsa.pub`
3.  Cmd/Ctrl + v @GitHub

## Peek-a-boo @Github (test)

`ssh -T git@github.com`

## @local (push setup)

(..only once per repo!)

```
git remote add origin git@github.com:sbissantz/test_dir.git
git remote add origin https://github.com/<username>/<new_repo>.git
git remote -v
```

## push!

- `git push -u origin master`
- `git push -u`
- `git push`

## help!

- `git help <verb>`
- `git help config`
- `git <verb> -h`

## ...in A Nutshell

1. `git init` (1x)
2. modify
3. `git add`
4. `git commit`
5. `git remote add origin` (1x)
6. `git push -u origin master`

## Your turn! (10 min)

1. Set up a remote repo @your_box
2. \{modiy, stage & push changes\}

\#BreakOutRooms!?

# Contribute!

1. fork! (@GitHub) 
2. clone! (@local)
3. push back! (@local)

## fork! (@GitHub!)

`> Repo > Fork (upper right)`

## clone! (@local) 

1. `git clone git@github.com:sbissantz/test_dir`
2. `cd test_dir`
3. `git remote -v`
4. `git remote add steven git@github.com/test_dir`

## push back! 

`git push -u steven git@github.com/test_dir`

## // vs. @

`git://github.com/` (read!)

vs

`git@github.com/` (+write!)

## Your turn! (10 min)

1. Clone a repostiry (e.g. `test_dir`) 
2. \{modify, stage, commit\} your changes
3. push back!

\#BreakOutRooms!?

# Accept proposals!

1. (establish connection)
1. pull!
  1. fetch!
  2. merge!
2. push back!

## (establish connections)
...if not done already!

```
git remote add steven git://github.com/steven/test_dir
```

## get them! 

`git fetch` + `git merge` = `git pull`

## git pull

- `git pull`
- `git pull steven master`

## push back!

- `git push`

## Note: Pull request?
...closes automatically!

## Your turn! (10 min)

1. Find a contributor! (e.g. `me`) 
2. Make him/her contribute!
3. Pull his/her changes!

\#BreakOutRooms!?

## Merge conflicts

1. `git pull steven master`
2. `gedit/nvim ` conflicting file (`<<to>>`)
3. `git add .`
4. `git commit`

# .gitignore
(aka. .git/config/excludes)

# GitHub Desktop

<https://desktop.github.com/>

## GitHub Desktop (install!)

`brew install --cask github`

## GitHub Desktop (tip)

`@GitHub > Code > Open with GitHub Desktop`

# Git & Rstudio

`> Tools > Global Option > Git/SVN`

# .aliases 
..useful to save keystrokes!

1. `which $SHELL`
2. edit: `.zshrc` or `.bashrc`
